### ISSUE TITLE
Connections errors with threaded Blockchain.stream()

### ISSUE THREAD

**Issue by crokkon** [holgern/beem#32]
#### Expected behavior
`b.stream(start=start, stop=stop, threading=True, thread_num=8)` should return all ops from the given block range and fetch the data with 8 threads in the background.

#### Actual behavior
The script throws lots of connection errors from various nodes and is comparably slow. Running the same call with `threading=False` works without any error and is typically even faster.

#### How to reproduce

```python
#!/usr/bin/python
from beem.blockchain import Blockchain
import sys
b = Blockchain()
opcount = 0
for op in b.stream(start=23483000, stop=23483200, threading=True, thread_num=8,
                   opNames=['vote']):
    sys.stdout.write("\r%s" % op['block_num'])
    opcount += 1
print("\n", opcount)
```

Output:
```
# time python bug_threading.py 
23483103Error: Invalid error code (_ssl.c:2273)
Lost connection or internal error on node: wss://steemd.pevo.science (1/-1) 

Error: rsv is not implemented, yet
Lost connection or internal error on node: wss://steemd.pevo.science (2/-1) 

Error: [Errno 9] Bad file descriptor
Error: Invalid WebSocket Header
Lost connection or internal error on node: wss://steemd.pevo.science (4/-1) 

Lost connection or internal error on node: wss://steemd.pevo.science (4/-1) 

Retrying in 5 seconds

Error: Handshake status 503 Service Temporarily Unavailable
Lost connection or internal error on node: wss://steemd.pevo.science (5/-1) 

Retrying in 6 seconds

Error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2273)
Lost connection or internal error on node: wss://steemd.pevo.science (6/-1) 

Error: Connection is already closed.
Lost connection or internal error on node: wss://steemd.pevo.science (7/-1) 

Retrying in 9 seconds

Error: Handshake status 503 Service Temporarily Unavailable
Lost connection or internal error on node: wss://steemd.pevo.science (8/-1) 

Retrying in 11 seconds

Error: Handshake status 503 Service Temporarily Unavailable
Lost connection or internal error on node: wss://steemd.pevo.science (9/-1) 

Retrying in 12 seconds

Error: Handshake status 503 Service Temporarily Unavailable
Lost connection or internal error on node: wss://steemd.pevo.science (10/-1) 

Retrying in 10 seconds

Error: rsv is not implemented, yet
Lost connection or internal error on node: wss://steemd.pevo.science (11/-1) 

Error: Connection is already closed.
Lost connection or internal error on node: wss://steemd.pevo.science (12/-1) 

Retrying in 10 seconds

23483255Error: Invalid error code (_ssl.c:2273)
Lost connection or internal error on node: wss://rpc.steemviz.com (1/-1) 

Error: [Errno 11] Resource temporarily unavailable
Lost connection or internal error on node: wss://rpc.steemviz.com (2/-1) 

Error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2273)
Error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2273)
Lost connection or internal error on node: wss://rpc.steemviz.com (4/-1) 

Retrying in 5 seconds

Lost connection or internal error on node: wss://rpc.steemviz.com (4/-1) 

Error: [Errno 9] Bad file descriptor
Lost connection or internal error on node: wss://rpc.steemviz.com (5/-1) 

Retrying in 6 seconds

Error: [Errno 9] Bad file descriptor
Lost connection or internal error on node: wss://rpc.steemviz.com (6/-1) 

Retrying in 8 seconds

Error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2273)
Error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2273)
Lost connection or internal error on node: wss://rpc.steemviz.com (8/-1) 

Lost connection or internal error on node: wss://rpc.steemviz.com (8/-1) 

Retrying in 11 seconds

Error: rsv is not implemented, yet
Error: rsv is not implemented, yet
Lost connection or internal error on node: wss://rpc.steemviz.com (10/-1) 

Lost connection or internal error on node: wss://rpc.steemviz.com (10/-1) 

Error: rsv is not implemented, yet
Lost connection or internal error on node: wss://rpc.steemviz.com (11/-1) 

Error: Invalid error code (_ssl.c:2273)
Lost connection or internal error on node: wss://rpc.steemviz.com (12/-1) 

Retrying in 10 seconds

Error: rsv is not implemented, yet
Lost connection or internal error on node: wss://rpc.steemviz.com (13/-1) 

Error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2273)
Lost connection or internal error on node: wss://rpc.steemviz.com (14/-1) 

Retrying in 10 seconds

Error: Connection is already closed.
Lost connection or internal error on node: wss://rpc.steemviz.com (15/-1) 

Retrying in 10 seconds

23483415Error: Invalid error code (_ssl.c:2273)
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (1/-1) 

Error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2273)
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (3/-1) 

Error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2273)
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (3/-1) 

Retrying in 3 seconds

Error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2273)
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (4/-1) 

Error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2273)
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (5/-1) 

Retrying in 6 seconds

Error: rsv is not implemented, yet
Error: Invalid error code (_ssl.c:2273)
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (7/-1) 

Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (7/-1) 

Retrying in 9 seconds

Error: Invalid error code (_ssl.c:2273)
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (8/-1) 

Error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2273)
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (9/-1) 

Error: [Errno 9] Bad file descriptor
Error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2273)
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (11/-1) 

Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (11/-1) 

Retrying in 10 seconds

Error: [Errno 9] Bad file descriptor
Error: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (13/-1) 

Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (13/-1) 

Retrying in 10 seconds

Error: [Errno 111] Connection refused
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (14/-1) 

Retrying in 10 seconds

Error: rsv is not implemented, yet
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (15/-1) 

Error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] Invalid error code (_ssl.c:2273)
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (16/-1) 

Retrying in 10 seconds

Error: [Errno 111] Connection refused
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (17/-1) 

Retrying in 10 seconds

Error: [Errno 111] Connection refused
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (18/-1) 

Retrying in 10 seconds

Error: [Errno 111] Connection refused
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (19/-1) 

Retrying in 10 seconds

Error: [Errno 111] Connection refused
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (20/-1) 

Retrying in 10 seconds

Error: [Errno 111] Connection refused
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (21/-1) 

Retrying in 10 seconds

Error: [Errno 111] Connection refused
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (22/-1) 

Retrying in 10 seconds

Error: [Errno 111] Connection refused
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (23/-1) 

Retrying in 10 seconds

Error: The read operation timed out
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (24/-1) 

Retrying in 10 seconds

Error: [Errno 111] Connection refused
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (25/-1) 

Retrying in 10 seconds

Error: [Errno 111] Connection refused
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (26/-1) 

Retrying in 10 seconds

Error: [Errno 111] Connection refused
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (27/-1) 

Retrying in 10 seconds

Error: [Errno 111] Connection refused
Lost connection or internal error on node: wss://steemd.minnowsupportproject.org (28/-1) 

Retrying in 10 seconds

23483500
 12230

real	4m40.085s
user	0m32.147s
sys	0m1.010s
```

The script takes considerably long to run and errors are shown from various nodes. The log (across several runs of the script above) contains errors I haven't seen before from typical node/connection issues:
```
Error: socket is already closed.
Error: rsv is not implemented, yet
Error: Handshake status 400 Bad Reest
Error: invalid literal for int() with base 10: '07:16:40'  # <- this was utcnow() at that time
Error: invalid literal for int() with base 10: 'Tm7e05+XYwFFwwm+UDClM9rFIfo='
Error: invalid literal for int() with base 10: '(Ubuntu)'
Error: Illegal frame
Error: ('Invalid opcode %r', 6)
Error: ('Underlying socket has been closed.',)
```

The same without threading:
```python
#!/usr/bin/python
from beem.blockchain import Blockchain
import sys
b = Blockchain()
opcount = 0
for op in b.stream(start=23483000, stop=23483500, threading=False, thread_num=8,
                   opNames=['vote']):
    sys.stdout.write("\r%s" % op['block_num'])
    opcount += 1
print("\n", opcount)
```
Output:
```
# time python bug_threading.py 
23483500
 12230

real	0m52.549s
user	0m15.767s
sys	0m0.527s
```

No connection error, and the single-threaded version is faster than the multi-threaded version.

#### Environment
```
# beempy --version
beempy, version 0.19.40
# python --version
Python 3.6.5
```

**Comment by crokkon** [comment]
I was playing around with explicitly setting nodes. The problem seem to be related to websocket connections. I wasn't able to reproduce it with https nodes, but using https is terribly slow compared to the single-threaded websocket variant.

**Comment by crokkon** [comment]
forcing separate `Steem()` instances per thread makes the errors disappear:
```diff
--- blockchain.py	2018-06-21 16:49:03.334766483 +0200
+++ ../../beem/beem/blockchain.py	2018-06-21 16:50:20.783045058 +0200
@@ -24,7 +24,6 @@
 from beemgraphenebase.py23 import py23_bytes
 from beem.instance import shared_steem_instance
 from .amount import Amount
-import beem as stm
 log = logging.getLogger(__name__)
 if sys.version_info < (3, 0):
     from Queue import Queue
@@ -424,9 +423,9 @@
                         block_num_list.append(blocknum + i)
                         results = []
                         if FUTURES_MODULE is not None:
-                            futures.append(pool.submit(Block, blocknum + i, only_ops=only_ops, only_virtual_ops=only_virtual_ops, steem_instance=stm.Steem()))
+                            futures.append(pool.submit(Block, blocknum + i, only_ops=only_ops, only_virtual_ops=only_virtual_ops, steem_instance=self.steem))
                         else:
-                            pool.enqueue(Block, blocknum + i, only_ops=only_ops, only_virtual_ops=only_virtual_ops, steem_instance=stm.Steem())
+                            pool.enqueue(Block, blocknum + i, only_ops=only_ops, only_virtual_ops=only_virtual_ops, steem_instance=self.steem)
                         i += 1
                     if FUTURES_MODULE is not None:
                         try:
```
...but also makes it terribly slow...

**Comment by holgern** [comment]
I tried to improve this in the newest commit, although it is not completely solved.

I added stream_threading_performance.py to examples.

**Comment by holgern** [comment]
@crokkon can you confirm that the bug is resolved now?

**Comment by crokkon** [comment]
I'm still seeing the same behavior. I believe the reason is here:
https://github.com/holgern/beem/blob/2e7d45bf2e8530cc24790aad591ca5060d9ed695/beemapi/graphenerpc.py#L265
All threads share the same Steem() instance, thus the same websocket connection.
`ws.send()` is threadsafe from upstream due to mutexes around `send` enabled via `enable_multithread=True`. So outgoing requests are handled sequentially, one at a time. However, `ws.recv()` is not threadsafe (and cannot be). If more than one request is open at a time, all concerning threads read from the same socketbuffer, each possibly getting data from the other requests. Data get's mixed up. I believe this is what we see with the strange error messages. I think the only way to really fix this is to have `thread_num` websocket connections, each handling a certain range of blocks. This should be doable technically, but requires quite some architectural changes...

**Comment by holgern** [comment]
This makes sense, In commit https://github.com/holgern/beem/commit/fe0bc6d51173d4aa5c83a2773e56c9163875b3a7 I created thread_num new Steem instances in a array:
 ```
            steem_instance = []
            for i in range(thread_num):
                steem_instance.append(stm.Steem(node=self.steem.rpc.nodes))
 ```
which are then used in:
```
                            futures.append(pool.submit(Block, blocknum + i, only_ops=only_ops, only_virtual_ops=only_virtual_ops, steem_instance=steem_instance[i]))
```

@crokkon can you test again?

**Comment by crokkon** [comment]
awesome! And simpler than I expected! I see no errors with 8 threads. 
I'm getting `Error: [Errno 111] Connection refused` for more than 10 threads, but maybe that's a node limit on the number of open connections allowed per client?

**Comment by holgern** [comment]
Seems to be a connection limitation
